### ISSUE TITLE
Update Sponsors page

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#261] opened 2015-12-01 22:17 UTC
Currently the sponsors page lists 2014's sponsors. We should update it to make it clear who is currently sponsoring us, and how to contact us if people are interested in sponsoring.

**Comment by marksteward** [comment] 2016-04-19 22:32
Almost dupe of #322, and similarly fixed by a53bf38..ea11631.

**Closed by marksteward** 2016-04-19 22:32 UTC
Labels: Copy, Needs input, Small
