### ISSUE TITLE
Sort out video schema

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#1297] opened 2024-01-04 18:49 UTC
schedule.json should include youtube_url but doesn't. It looks like we've added a video section manually instead. These should move into the DB and the matcher should be updated and documented.

We should also update the .frab files at the same time, and pretty-print the schedule.jsons (why aren't they already, when the rest of the exports are?)

**Comment by russss** [comment] 2024-01-04 18:55
This is actually broadly a duplicate of #831, which I filed when I revamped all this in 2019.

**Closed by russss** 2024-01-04 18:55 UTC
