### ISSUE TITLE
Email CSS inlining is failing

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1440] opened 2024-04-19 19:09 UTC
```
website-app-1  | 2024-04-19 19:03:58,722 main         ERROR    57 russ@garrett.co.uk Unhandled exception in request: <Request 'https://www.emfcamp.org/admin/product_views/2/voucher/bulk_add' [POST]>
website-app-1  | Traceback (most recent call last):
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
website-app-1  |     rv = self.dispatch_request()
website-app-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
website-app-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
website-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/app/apps/admin/products.py", line 615, in product_view_bulk_add_vouchers_by_email
website-app-1  |     preview = format_trusted_html_email(
website-app-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/app/apps/common/email.py", line 101, in format_trusted_html_email
website-app-1  |     return inline_css(
website-app-1  |            ^^^^^^^^^^^
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/inlinestyler/utils.py", line 17, in inline_css
website-app-1  |     converter.perform(document, html_message, '', encoding=encoding)
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/inlinestyler/converter.py", line 30, in perform
website-app-1  |     matching = CSSRelSelector.evaluate(document)
website-app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  | AttributeError: 'CSSSelector' object has no attribute 'evaluate'
```

**Comment by marksteward** [comment] 2024-04-19 23:16
Caused by https://github.com/dlanger/inlinestyler/issues/32. Fixed by switching to css-inline with 28fa762.

**Closed by marksteward** 2024-04-19 23:16 UTC
