### ISSUE TITLE
Generate per-year schedule urls for proposals and use in emails

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#1177] opened 2022-05-26 23:59 UTC
Each proposal should have a unique path (`schedule/<year>/<proposal-id>`). These should be generated for each proposal and used in the slot machine schedule emails (`templates/emails/cfp-slot-{moved,scheduled}.txt`) rather than the current hard coded fix

**Comment by lukegb** [comment] 2024-01-29 22:26
Duplicate of #1175.

**Closed by lukegb** 2024-01-29 22:26 UTC
Labels: 📝CfP, bug
