### ISSUE TITLE
Only allow people with an approved CfP proposal to purchase speaker tickets

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#409] opened 2016-07-11 18:57 UTC
This avoids speakers sharing their discount code. This could just be a flag in the ticket_type table which restricts it to confirmed speakers.

Ideally, it would be nice to _automatically_ offer tickets to people with a confirmed speaker slot, but this might result in people who already have a ticket buying another one and selling their current ticket to a friend. This bit needs some additional thought.

**Comment by Jonty** [comment] 2016-07-12 09:20
Note: It's not quite as simple as this (although we should have this ability to make it so we don't have to manually hand out the tickets) - some submissions have more than one person required to operate/show them, but we currently only have one relationship to the person who submitted it.

**Comment by russss** [comment] 2016-07-12 09:54
Yes, although I'd argue that's over-thinking it, as this would solve 90% of the manual ticket issuing.

**Comment by Jonty** [comment] 2016-07-12 10:06
I was more saying that we need to keep the ability to issue speaker tickets to people without submissions for exceptional cases, not that we should build multi-speaker things

**Comment by russss** [comment] 2016-07-12 10:07
Yes, which will still be possible by creating another ticket discount code.

**Comment by marksteward** [comment] 2018-08-05 22:49
Dupe of #655 as far as I can tell.

**Closed by marksteward** 2018-08-05 22:49 UTC
Labels: Nice-to-have, Tickets
