### ISSUE TITLE
Allow recharging of a payment at the same price

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#181] opened 2014-07-07 23:19 UTC
To allow repayment after things go wrong. We can then direct user to complete payment. 
Alternatively, we can add a ticket_token and let them buy the ticket from the start again.

Particularly important for the people who got early bird tickets. Otherwise could be made possible only for Stripe (declined cards are impossible to recover from) and cancelled payments?

**Comment by marksteward** [comment] 2015-12-14 21:20
Prod anyone who got a declined card after this is fixed.

**Comment by russss** [comment] 2016-03-06 10:13
I'm actually a bit confused about what this means. Stripe payments *can* be re-charged - if your card is declined then the popover gives you a chance to enter another. 

And in any case, you can get back to your old payments through /tickets/ and restart the payment through the same provider.

So I think the only issue is that you can't change payment provider once your order is created, which is I believe a duplicate of #152. De-milestoning.

**Closed as completed** 2018-07-22 23:24 UTC
Labels: Admin
