### ISSUE TITLE
Schedule popup text unusable on mobile phones

### ISSUE THREAD

**Issue by nomis** [emfcamp/Website#460] opened 2016-08-09 22:58 UTC
Using Chrome on a Nexus 5, the popup text for an event is unusable because the space allocated to the scrolling text was usually less than half a line (depending on the length of the event title) requiring very awkward scrolling to read it.

**Comment by Jonty** [comment] 2016-08-09 23:01
We're really sorry about this - we just didn't have time to fix it once the event got into full swing!

**Comment by marksteward** [comment] 2018-01-20 14:05
See also #457

**Comment by SamLR** [comment] 2020-02-06 21:38
Closing as duplicate of #457

**Closed by SamLR** 2020-02-06 21:38 UTC
Labels: ⏱Schedule
