### ISSUE TITLE
CFP finalise form loses all your changes if a field does not validate

### ISSUE THREAD

**Issue by davidc** [emfcamp/Website#1152] opened 2022-05-18 12:32 UTC
Go to https://www.emfcamp.org/cfp/proposals/187/finalise
Change some stuff
Enter a field that is invalid (I entered GDPR for on-site extension)

The form reloads and the field is highlighted showing the error. However every change that I made on the previous page has been lost.

Expected behaviour: It should keep all the fields that I edited, not reload them from the database.

**Comment by marksteward** [comment] 2022-05-19 19:19
Fixed by 70ebe81

**Closed by marksteward** 2022-05-19 19:19 UTC

**Comment by marksteward** [comment] 2022-05-19 19:36
So the thing I was thinking of wasn't actually the cause. We're still not initialising forms using `obj=` and persisting them with `populate_obj` for the CfP currently, but changing that is a bit of a mammoth task that involves renaming form element names and deleting stuff based on the CfP type. May not be worth doing in the long run.
